[database]
url = "sashiko.db"
token = ""

[nntp]
server = "nntp.lore.kernel.org"
port = 119
groups = ["org.kernel.vger.linux-kernel"]

[ai]
provider = "gemini"
model = "gemini-3-flash-preview"

[server]
host = "127.0.0.1"
port = 8080

[git]
repository_path = "linux"

[review]
concurrency = 20
worktree_dir = "review_trees"